export default {
  'Amy': 10,
  'Anubis': 1,
  'Armos': 1,
  'Baby Dodongo': 1,
  'Door Mimic': 1,
  'Bari': 1,
  'Barinade': 20,
  'Beth': 10,
  'Beamos': 1,
  'Big Deku Baba': 1,
  'Big Octo': 15,
  'Big Poe': 5,
  'Big Skulltula': 1,
  'Biri': 1,
  'Blue Bubble': 5,
  'Blue Tektite': 1,
  'Bongo Bongo': 30,
  'Business Scrub': 1,
  'Club Moblin': 1,
  'Dark Link': 1,
  'Dead Hand': 15,
  'Deku Baba': 1,
  'Deku Scrub': 1,
  'Dinolfos': 10,
  'Dodongo': 20,
  'Fire Keese': 1,
  'Flare Dancer': 15,
  'Flat': 1,
  'Floormaster': 1,
  'Freezard': 1,
  'Ganon': 40,
  'Ganondorf': 1,
  'Gerudo Thief': 10,
  'Giant Leever': 5,
  'Gibdo': 1,
  'Gohma': 20,
  'Gohma Larva': 1,
  'Gold Skulltula': 1,
  'Green Bubble': 5,
  'Guay': 1,
  'Ice Keese': 1,
  'Invisible Floormaster': 15,
  'Iron Knuckle': 15,
  'Joelle': 10,
  'Keese': 1,
  'King Dodongo': 20,
  'Leever': 1,
  'Like Like': 1,
  'Lizalfos': 5,
  'Mad Scrub': 1,
  'Meg': 10,
  'Moblin': 1,
  'Morpha': 30,
  'Nabooru Knuckle': 20,
  'Octorok': 1,
  'Parasitic Tentacle': 1,
  'Peahat': 1,
  'Peahat Larva': 1,
  'Phantom Ganon': 30,
  'Poe': 1,
  'ReDead': 1,
  'Red Bubble': 5,
  'Red Tektite': 1,
  'Shabom': 1,
  'Sharp': 1,
  'Shell Blade': 1,
  'Skulltula': 1,
  'Skullwalltula': 1,
  'Skull Kid': 1,
  'Spike': 1,
  'Stalchild': 1,
  'Stalfos': 10,
  'Stinger': 1,
  'Tailpasaran': 1,
  'Torch Slug': 1,
  'Twinrova': 30,
  'Volvagia': 30,
  'Wallmaster': 1,
  'White Bubble': 5,
  'White Wolfos': 1,
  'Wolfos': 1
};
