export default [
  'Amy',
  'Anubis',
  'Armos',
  'Baby Dodongo',
  'Door Mimic',
  'Bari',
  'Barinade',
  'Beth',
  'Beamos',
  'Big Deku Baba',
  'Big Octo',
  'Big Poe',
  'Big Skulltula',
  'Biri',
  'Blue Bubble',
  'Blue Tektite',
  'Bongo Bongo',
  'Business Scrub',
  'Club Moblin',
  'Dark Link',
  'Dead Hand',
  'Deku Baba',
  'Deku Scrub',
  'Dinolfos',
  'Dodongo',
  'Fire Keese',
  'Flare Dancer',
  'Flat',
  'Floormaster',
  'Freezard',
  'Ganon',
  'Ganondorf',
  'Gerudo Thief',
  'Gibdo',
  'Gohma',
  'Gohma Larva',
  'Gold Skulltula',
  'Green Bubble',
  'Guay',
  'Ice Keese',
  'Iron Knuckle',
  'Joelle',
  'Keese',
  'King Dodongo',
  'Leever',
  'Like Like',
  'Lizalfos',
  'Mad Scrub',
  'Meg',
  'Moblin',
  'Morpha',
  'Nabooru Knuckle',
  'Octorok',
  'Parasitic Tentacle',
  'Peahat',
  'Peahat Larva',
  'Phantom Ganon',
  'Poe',
  'Poe',
  'ReDead',
  'Red Bubble',
  'Red Tektite',
  'Shabom',
  'Sharp',
  'Shell Blade',
  'Skulltula',
  'Skullwalltula',
  'Skull Kid',
  'Spike',
  'Stalchild',
  'Stalfos',
  'Stinger',
  'Tailpasaran',
  'Torch Slug',
  'Twinrova',
  'Volvagia',
  'Wallmaster',
  'White Bubble',
  'White Wolfos',
  'Wolfos'
];
